root: true
parser: babel-eslint
extends:
  - semistandard
  - plugin:prettier/recommended
rules:
  standard/computed-property-even-spacing: off
parserOptions:
  sourceType: script
overrides:
  - files:
      - .mocharc.js
    parserOptions:
      sourceType: script
  - files:
      - test/**/*.spec.js
    env:
      mocha: true
